### ISSUE TITLE
When trying to compress/decompress Unicode the string can't be recovered.

### ISSUE THREAD

**Issue by jefferson-kaneta-oktagon** [Hitcents/Unity-System.IO.Compression#1]
I tried to compress and uncompress unicode strings based on the tests you created for unity.
But when decoding the string it only returns me junk.
I used base64 to convert and recovert the compressed string.

**Comment by jonathanpeppers** [comment]
Can you paste some source code?

I would recommend trying what Microsoft is doing [here](https://msdn.microsoft.com/en-us/library/system.io.compression.gzipstream%28v=vs.110%29.aspx). Change the using from `System.IO.Compression` to `Unity.IO.Compression`.
