### ISSUE TITLE
Failed to return the text I inputed

### ISSUE THREAD

**Issue by infosekr** [Hitcents/Unity-System.IO.Compression#2]
I have the following methods to compress and uncompress some text:

```
    public static byte[] CompressText(string text)
    {
        byte[] byteData = Encoding.ASCII.GetBytes(text);

        using (var memoryStream = new MemoryStream())
        {
            using (var gzip = new GZipStream(memoryStream, CompressionMode.Compress))
            using (var writer = new StreamWriter(gzip))
            {
                writer.Write(byteData);
            }
            return memoryStream.ToArray();
        }
    }

    public static string DecompressText(byte[] byteData)
    {
        using (var memoryStream = new MemoryStream())
        {
            using (var deflate = new DeflateStream(memoryStream, CompressionMode.Compress))
            using (var writer = new StreamWriter(deflate))
            {
                writer.Write(byteData);
            }
            return ASCIIEncoding.ASCII.GetString(memoryStream.ToArray());
        }
    }
```

I compress 307 characters of Json into 136 bytes. When I decompress the data it's 118 characters and junk.

I'm using Unity 5.3.1f. Am I doing something wrong with this code, or is this a bug?

**Comment by jonathanpeppers** [comment]
It doesn't look like your code above is quite right, you have `Compress` on the Decompress method and are using a `StreamWriter`. I think you need `StreamReader` instead.

Can you verify that your code works under normal .NET? just a Console program in Visual Studio? The only difference would be the `using` statement is `System.IO.Compression` in .NET instead of `Unity.IO.Compression`.

**Comment by infosekr** [comment]
This is the example code that is provided with the unity package. An exception was raised if I used CompressionMode.Decompress, something to the effect that decompress is not supported. I assumed it needed to be a StreamWriter because it needs to write out new data from the decompress operation.

**Comment by infosekr** [comment]
![untitled](https://cloud.githubusercontent.com/assets/885632/12794285/2fb4b280-ca69-11e5-93e8-07287fa2f82b.png)

**Comment by jonathanpeppers** [comment]
So the screenshot above is two examples of compressing, not an example of decompressing.

Can you try in a .NET console program?

**Comment by infosekr** [comment]
Ok, I must have been confused. I thought by using the DeflateStream this was doing the decompression.Maybe it would be useful to update this image with some comments, or add in some example code in the project.
Feel free to delete my issue on github, I'm using a different compression solution now. 

```
On Monday, February 8, 2016 11:48 AM, Jonathan Peppers <notifications@github.com> wrote:
```

 So the screenshot above is two examples of compressing, not an example of decompressing.Can you try in a .NET console program?—

**Comment by jonathanpeppers** [comment]
Ok, no problem.

My stance with the documentation for this library was to just fallback to Microsoft's in System.IO.Compression [here](https://msdn.microsoft.com/en-us/library/system.io.compression%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396). I am actually using the code Microsoft open-sourced from the .Net framework with minor changes to run in Unity. I use standard .Net as much as Unity, so I felt it would be something people were used to.

In the long term, I would actually prefer Unity to just fix the System.IO.Compression namespace in Unity. I have the code right here. If I can do it, they can do it.

**Comment by infosekr** [comment]
Ah yeah makes sense. I knew it was using .net source, but i forgot to look at the .net docs.Yeah it would be great if this was inside Unity.
Thanks for replying to my issue.
Best Regards,Aaron 

```
On Tuesday, February 9, 2016 10:03 AM, Jonathan Peppers <notifications@github.com> wrote:
```

 Ok, no problem.My stance with the documentation for this library was to just fallback to Microsoft's in System.IO.Compression here. I am actually using the code Microsoft open-sourced from the .Net framework with minor changes to run in Unity. I use standard .Net as much as Unity, so I felt it would be something people were used to.In the log term, I would actually prefer Unity to just fix the System.IO.Compression namespace in Unity. I have the code right here. If I can do it, they can do it.—
