### ISSUE TITLE
`Release` branch to easily access source files only

### ISSUE THREAD

**Issue by Geri-Borbas** [Hitcents/Unity-System.IO.Compression#4]
Hi,
thanks for this!

Could you maintain a `Release` brach, where you publish the source files only (I mean this folder https://github.com/Hitcents/Unity.IO.Compression/tree/master/Assets/Unity.IO.Compression).

I'm thinking something like I do here:
This is the whole project at `master`:
https://github.com/eppz/Triangle.NET

And this is the source only at `Release`:
https://github.com/eppz/Triangle.NET/tree/Release

The latter is suitable to be attached directly as a submodule for further projects.
See the attached `Release` branch here: https://github.com/eppz/Unity.Library.eppz.Geometry

**Comment by jonathanpeppers** [comment]
Sorry, I no longer work for Hitcents and I do not have access to this repo anymore...

I'm not sure anyone is maintaining this, but it should be fine to still use... it is based off Microsoft source code.

**Comment by Geri-Borbas** [comment]
Thanks for getting back. I'll fork then, and maintain branch there.

**Comment by Geri-Borbas** [comment]
There it goes: https://github.com/eppz/Unity.IO.Compression/tree/Release
Thanks again! 🙌
